name: android-build
on: 
  push:
    branches:
      - main
    paths:
      - android/*
      - lib/*
  pull_request:
    branches:
      - main
jobs:
  build_with_signing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
         java-version: '12.x'
      - name: build app
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' #dev, alpha, beta...
      - run: ./build.sh
      
