name: webconsole-test

on:
  push:
    branches: [ webconsole ]
  pull_request:
    branches: [ webconsole ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd web-console
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Application
      run: |
        cd web-console
        docker-compose up --build
        echo "Build successful without errors"
        exit 0
